<?php

namespace Core\Basket;

use App\Global\Business\DTO\ClientDTO;
use App\Global\Persistence\Repository\ClientRepository;
use App\Global\Persistence\SQL\SqlConnector;
use App\User\Components\Basket\Business\DTO\BasketDTO;
use App\User\Components\Basket\Business\Manipulation\BasketManipulator;
use App\User\Components\Basket\Persistence\Repository\BasketRepository;
use App\User\Components\Registration\Persistence\Entity\ClientEntityManager;
use PHPUnit\Framework\TestCase;

class BasketManipulatorTest extends TestCase
{
    public SqlConnector $sqlConnector;
    public ClientRepository $clientRepository;
    public BasketRepository $basketRepository;
    public ClientEntityManager $clientEntityManager;
    public BasketManipulator $basketManipulator;
    public function setUp(): void
    {
        $this->clientRepository = new ClientRepository();
        $this->sqlConnector = new SqlConnector();
        $this->basketRepository = new BasketRepository();
        $this->clientEntityManager = new ClientEntityManager();
        $this->basketManipulator = new BasketManipulator();

        $ClientDTO = new ClientDTO();
        $ClientDTO->username = 'TEST';
        $ClientDTO->email = 'TEST@TEST.com';
        $ClientDTO->password = 'QWERTZ';

        $this->clientEntityManager->saveCredentials($ClientDTO);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAddItemToBasket() : void
    {
        $_GET['id'] = '44';
        $_SESSION['mail'] = 'TEST@TEST.com';
        $this->basketManipulator->addItemToBasket();

        $basket = $this->basketRepository->getBasketInfo();

        self::assertInstanceOf(BasketDTO::class, $basket[0]);
        self::assertSame('Cristiano Ronaldo Trikot', $basket[0]->name);
    }

    public function testRemoveItemFromBasket() : void
    {
        $_GET['id'] = '44';
        $_SESSION['mail'] = 'TEST@TEST.com';
        $this->basketManipulator->addItemToBasket();

        $this->basketManipulator->removeItemFromBasket();

        $basket = $this->basketRepository->getBasketInfo();

        self::assertEmpty($basket);
    }

        public function tearDown(): void
    {
        $connector = new SqlConnector();
        $connector->executeDeleteQuery("DELETE FROM user_baskets;", []);
        $connector->executeDeleteQuery("DELETE FROM users;", []);
        $connector->closeConnection();
        parent::tearDown();
    }
}