<?php

namespace Core;

use App\Global\Presentation\TemplateEngine\TemplateEngine;
use PHPUnit\Framework\TestCase;

class TemplateEngineTest extends TestCase
{
    public TemplateEngine $templateEngine;

    public function setUp(): void
    {
        $this->templateEngine = new TemplateEngine(__DIR__ . '/../../tests/View');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testDisplay() : void
    {
        $this->templateEngine->setTemplate('test.twig');
        $this->templateEngine->addParameter('name', 'Nico');

        ob_start();
        $this->templateEngine->display();
        $output = ob_get_clean();

        $this->assertStringContainsString('Hi, Nico', $output);
    }
    public function testGetParameters() : void
    {
        $this->templateEngine->setTemplate('test.twig');
        $this->templateEngine->addParameter('name', 'Nico');

        self::assertSame(['name' => 'Nico'], $this->templateEngine->getParameters());
    }

    public function testGetTemplate() : void
    {
        $this->templateEngine->setTemplate('test.twig');
        $this->templateEngine->addParameter('name', 'Nico');

        self::assertSame('test.twig', $this->templateEngine->getTpl());
    }
}