<?php

namespace Core;

use App\Components\Basket\Business\Manipulation\TotalManipulator;
use App\Components\Basket\Persistence\Repository\BasketRepository;
use App\Components\Order\Persistence\Entity\OrderEntityManager;
use App\Components\Order\Persistence\Repository\OrderRepository;
use App\Components\UserRegistration\Persistence\UserEntityManager;
use App\Components\UserSession\Persistence\UserRepository;
use App\Global\Business\DTO\ClientDTO;
use App\Global\Persistence\SQL\SqlConnector;
use PHPUnit\Framework\TestCase;

class TotalCalculatorTest extends TestCase
{
    public SqlConnector $sqlConnector;
    public UserRepository $clientRepository;
    public BasketRepository $basketRepository;
    public UserEntityManager $clientEntityManager;
    public OrderEntityManager $orderEntityManager;
    public OrderRepository $orderRepository;
    public TotalManipulator $totalCalculator;

    public function setUp(): void
    {
        $this->clientRepository = new UserRepository();
        $this->sqlConnector = new SqlConnector();
        $this->basketRepository = new BasketRepository();
        $this->clientEntityManager = new UserEntityManager();
        $this->orderEntityManager = new OrderEntityManager();
        $this->orderRepository = new OrderRepository();
        $this->totalCalculator = new TotalManipulator();

        $ClientDTO = new ClientDTO();
        $ClientDTO->username = 'TEST';
        $ClientDTO->email = 'TEST@TEST.com';
        $ClientDTO->password = '$2y$10$hfMft79lTEeHSDGsMf91s.iJcUTgVoIHnUQVGfxleSTXARmpr7nN6';

        $this->clientEntityManager->saveCredentials($ClientDTO);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCalculateTotalValid(): void
    {
        $_SESSION['mail'] = 'TEST@TEST.com';

        $_SESSION['delivery'] = 'DHL';
        $totalDHL = $this->totalCalculator->calculateTotal();

        $_SESSION['delivery'] = 'DPD';
        $totalDPD = $this->totalCalculator->calculateTotal();

        $_SESSION['delivery'] = 'FedEX';
        $totalFedEX = $this->totalCalculator->calculateTotal();

        self::assertSame(4.95, $totalDHL);
        self::assertSame(3.95, $totalDPD);
        self::assertSame(9.95, $totalFedEX);

    }

    public function testCalculateTotalInvalidDeliveryDeclared(): void
    {
        $_SESSION['mail'] = 'TEST@TEST.com';

        $_SESSION['delivery'] = 'INVALID';
        $total = $this->totalCalculator->calculateTotal();

        self::assertSame(0.00, $total);
    }

    public function tearDown(): void
    {
        $connector = new SqlConnector();
        $connector->executeDeleteQuery("DELETE FROM orders;", []);
        $connector->executeDeleteQuery("DELETE FROM user_baskets;", []);
        $connector->executeDeleteQuery("DELETE FROM users;", []);
        $connector->closeConnection();
        parent::tearDown();
    }

}