<?php

namespace Core\Session;

use App\Core\Session\SessionHandler;
use PHPUnit\Framework\TestCase;

class SessionHandlerTest extends TestCase
{
    public SessionHandler $sessionHandler;

    public function setUp(): void
    {
        $this->sessionHandler = new SessionHandler();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testSetSession() : void
    {
        $this->sessionHandler->setSession('');

        $sessionID = session_id();

        self::assertNotEmpty($sessionID);
    }
    public function testGetOrderSessionValidInput() : void
    {
        $_SESSION['first_name'] = 'firstName';
        $_SESSION['last_name'] = 'lastName';
        $_SESSION['address'] = 'address';
        $_SESSION['city'] = 'city';
        $_SESSION['zip'] = 'zip';
        $_SESSION['delivery'] = 'delivery';
        $_SESSION['payment'] = 'payment';
        $_SESSION['mail'] = 'mail@mail.com';

        $order = $this->sessionHandler->getOrderSession();

        self::assertSame('firstName', $order['firstName']);
        self::assertSame('lastName', $order['lastName']);
        self::assertSame('address', $order['address']);
        self::assertSame('city', $order['city']);
        self::assertSame('zip', $order['zip']);
        self::assertSame('delivery', $order['delivery']);
        self::assertSame('payment', $order['payment']);
        self::assertSame('mail@mail.com', $order['email']);
    }

    public function testGetOrderSessionNoInput() : void
    {
        $_SESSION['first_name'] = '';
        $_SESSION['last_name'] = '';
        $_SESSION['address'] = '';
        $_SESSION['city'] = '';
        $_SESSION['zip'] = '';
        $_SESSION['delivery'] = '';
        $_SESSION['payment'] = '';
        $_SESSION['mail'] = '';

        $order = $this->sessionHandler->getOrderSession();

        self::assertSame('', $order['firstName']);
        self::assertSame('', $order['lastName']);
        self::assertSame('', $order['address']);
        self::assertSame('', $order['city']);
        self::assertSame('', $order['zip']);
        self::assertSame('', $order['delivery']);
        self::assertSame('', $order['payment']);
        self::assertSame('', $order['email']);
    }

    public function tearDown(): void
    {
        if (!empty(session_id())) {
            session_destroy();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}