<?php

namespace Model;

use App\Components\Basket\Persistence\Repository\BasketRepository;
use App\Components\UserRegistration\Persistence\UserEntityManager;
use App\Components\UserSession\Persistence\UserRepository;
use App\Global\Business\Dependency\Container;
use App\Global\Business\Dependency\DependencyProvider;
use App\Global\Business\DTO\ClientDTO;
use App\Global\Persistence\SQL\SqlConnector;
use PHPUnit\Framework\TestCase;

class ClientEntityManagerTest extends TestCase
{
    public SqlConnector $sqlConnector;
    public UserRepository $userRepository;
    public BasketRepository $basketRepository;
    public UserEntityManager $userEntityManager;
    public function setUp(): void
    {
        $container = new Container();
        $provider = new DependencyProvider();
        $provider->provide($container);

        $this->userRepository = $container->get(UserRepository::class);
        $this->sqlConnector = $container->get(SqlConnector::class);
        $this->userEntityManager = $container->get(UserEntityManager::class);

        $ClientDTO = new ClientDTO();
        $ClientDTO->username = 'TEST';
        $ClientDTO->email = 'TEST@TEST.com';
        $ClientDTO->password = 'QWERTZ';

        $this->userEntityManager->saveCredentials($ClientDTO);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testSaveCredentials() : void
    {
        $ClientDTO = $this->userRepository->findByMail('TEST@TEST.com');

        self::assertInstanceOf(ClientDTO::class, $ClientDTO);
        self::assertSame('TEST', $ClientDTO->username);
        self::assertSame('TEST@TEST.com', $ClientDTO->email);
        self::assertSame('QWERTZ', $ClientDTO->password);
    }


    public function tearDown(): void
    {
        $connector = new SqlConnector();
        $connector->executeDeleteQuery("DELETE FROM user_baskets;", []);
        $connector->executeDeleteQuery("DELETE FROM users;", []);
        $connector->closeConnection();
        parent::tearDown();
    }
}