<?php

namespace Model;

use App\Components\Basket\Persistence\Entity\BasketEntityManager;
use App\Components\Basket\Persistence\Repository\BasketRepository;
use App\Components\Order\Persistence\Entity\OrderEntityManager;
use App\Components\Order\Persistence\Repository\OrderRepository;
use App\Components\UserRegistration\Persistence\UserEntityManager;
use App\Components\UserSession\Persistence\UserRepository;
use App\Global\Business\Dependency\Container;
use App\Global\Business\Dependency\DependencyProvider;
use App\Global\Business\DTO\ClientDTO;
use App\Global\Business\DTO\OrderDTO;
use App\Global\Persistence\SQL\SqlConnector;
use PHPUnit\Framework\TestCase;

class OrderEntityManagerTest extends TestCase
{
    public SqlConnector $sqlConnector;
    public UserRepository $userRepository;
    public BasketRepository $basketRepository;
    public UserEntityManager $userEntityManager;
    public OrderEntityManager $orderEntityManager;
    public OrderRepository $orderRepository;
    public BasketEntityManager $basketEntityManager;

    public function setUp(): void
    {
        $container = new Container();
        $provider = new DependencyProvider();
        $provider->provide($container);

        $this->userRepository = $container->get(UserRepository::class);
        $this->sqlConnector = $container->get(SqlConnector::class);
        $this->basketRepository = $container->get(BasketRepository::class);
        $this->userEntityManager = $container->get(UserEntityManager::class);
        $this->basketEntityManager = $container->get(BasketEntityManager::class);
        $this->orderEntityManager = $container->get(OrderEntityManager::class);
        $this->orderRepository = $container->get(OrderRepository::class);

        $ClientDTO = new ClientDTO();
        $ClientDTO->username = 'TEST';
        $ClientDTO->email = 'TEST@TEST.com';
        $ClientDTO->password = '$2y$10$hfMft79lTEeHSDGsMf91s.iJcUTgVoIHnUQVGfxleSTXARmpr7nN6';

        $this->userEntityManager->saveCredentials($ClientDTO);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testSaveOrderValid() : void
    {
        $_SESSION['mail'] = 'TEST@TEST.com';

        $orderDTO = new OrderDTO();
        $orderDTO->email = 'TEST@TEST.com';
        $orderDTO->firstName = 'TEST-FIRST';
        $orderDTO->lastName = 'TEST-LAST';
        $orderDTO->zip = '1337';
        $orderDTO->city = 'TEST-CITY';
        $orderDTO->address = 'TEST-ADDRESS';
        $orderDTO->paymentMethod = 'TEST-PAYMENT';
        $orderDTO->delivery = 'TEST-DELIVERY';

        $this->basketEntityManager->addToBasket('44', $this->userRepository->getUserID($_SESSION['mail']));

        $result = $this->orderEntityManager->saveOrder($orderDTO);

        $sqlSelectArray = $this->sqlConnector->executeSelectQuery('SELECT * FROM orders', []);

        self::assertNotEmpty($result);
        self::assertSame('{"id": "44", "quantity": "1"}', $sqlSelectArray[0]['items']);
        self::assertSame('TEST-FIRST', $sqlSelectArray[0]['firstName']);
        self::assertSame('TEST-LAST', $sqlSelectArray[0]['lastName']);
        self::assertSame('1337', $sqlSelectArray[0]['zip']);
        self::assertSame('TEST-CITY', $sqlSelectArray[0]['city']);
        self::assertSame('TEST-DELIVERY', $sqlSelectArray[0]['delivery']);
        self::assertSame('TEST-PAYMENT', $sqlSelectArray[0]['payment']);
    }


    public function tearDown(): void
    {
        $connector = new SqlConnector();
        $connector->executeDeleteQuery("DELETE FROM orders;", []);
        $connector->executeDeleteQuery("DELETE FROM user_baskets;", []);
        $connector->executeDeleteQuery("DELETE FROM users;", []);
        $connector->closeConnection();
        parent::tearDown();
    }
}