<?php

namespace Controller;

use App\Controller\BasketController;
use App\Controller\ThankYouController;
use App\Core\Container;
use App\Core\DependencyProvider;
use App\Core\DTO\BasketDTO;
use App\Core\DTO\ClientDTO;
use App\Core\DTO\OrderDTO;
use App\Core\SQL\SqlConnector;
use App\Model\BasketRepository;
use App\Model\ClientEntityManager;
use App\Model\ClientRepository;
use App\Model\OrderEntityManager;
use App\Model\OrderRepository;
use PHPUnit\Framework\TestCase;
use function PHPUnit\Framework\assertSame;

class BasketControllerTest extends TestCase
{
    public ThankYouController $thankYouController;
    public SqlConnector $sqlConnector;
    public ClientRepository $clientRepository;
    public BasketRepository $basketRepository;
    public ClientEntityManager $clientEntityManager;
    public OrderEntityManager $orderEntityManager;
    public OrderRepository $orderRepository;

    public function setUp(): void
    {
        $this->clientRepository = new ClientRepository();
        $this->sqlConnector = new SqlConnector();
        $this->basketRepository = new BasketRepository();
        $this->clientEntityManager = new ClientEntityManager();
        $this->orderEntityManager = new OrderEntityManager();
        $this->orderRepository = new OrderRepository();

        $ClientDTO = new ClientDTO();
        $ClientDTO->username = 'TEST';
        $ClientDTO->email = 'TEST@TEST.com';
        $ClientDTO->password = '$2y$10$hfMft79lTEeHSDGsMf91s.iJcUTgVoIHnUQVGfxleSTXARmpr7nN6';

        $this->clientEntityManager->saveCredentials($ClientDTO);

        $containerBuilder = new Container();
        $dependencyProvider = new DependencyProvider();
        $dependencyProvider->provide($containerBuilder);

        $this->construct = new BasketController($containerBuilder);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testDataConstructAdd(): void
    {
        $_GET['action'] = 'add';
        $_SESSION['mail'] = 'TEST@TEST.com';
        $_GET['id'] = '44';

        $this->construct->dataConstruct();

        self::assertSame('basket.twig', $this->construct->dataConstruct()->getTpl());
        self::assertInstanceOf(BasketDTO::class, $this->construct->dataConstruct()->getParameters()['contents'][0]);
        self::assertSame('Cristiano Ronaldo Trikot', $this->construct->dataConstruct()->getParameters()['contents'][0]->name);
        self::assertSame('149.95', $this->construct->dataConstruct()->getParameters()['total']);

    }

    public function testDataConstructRemove(): void
    {
        $_GET['action'] = 'remove';
        $_SESSION['mail'] = 'TEST@TEST.com';
        $_GET['id'] = '44';

        $this->clientEntityManager->addToBasket('44', $this->clientRepository->getUserID($_SESSION['mail']));
        $this->construct->dataConstruct();

        self::assertSame('basket.twig', $this->construct->dataConstruct()->getTpl());
        self::assertIsArray($this->construct->dataConstruct()->getParameters()['contents']);
        self::assertEmpty($this->construct->dataConstruct()->getParameters()['contents']);
        self::assertEmpty($this->construct->dataConstruct()->getParameters()['total']);
    }

    public function tearDown(): void
    {
        $connector = new SqlConnector();
        $connector->executeDeleteQuery("DELETE FROM orders;", []);
        $connector->executeDeleteQuery("DELETE FROM user_baskets;", []);
        $connector->executeDeleteQuery("DELETE FROM users;", []);
        $connector->closeConnection();
        parent::tearDown();
    }

}