<?php

namespace Controller;

use App\Controller\ClientLoginController;
use App\Controller\ClientLogoutController;
use App\Core\DependencyProvider;
use App\Core\SQL\SqlConnector;
use PHPUnit\Framework\TestCase;
use App\Core\Container;

class ClientLogoutControllerTest extends TestCase
{
    protected function setUp(): void
    {
        $containerBuilder = new Container();
        $dependencyProvider = new DependencyProvider();
        $dependencyProvider->provide($containerBuilder);

        $this->container = $containerBuilder;
        $this->construct = new ClientLogoutController($this->container);

        parent::setUp();
    }

    public function testDataConstruct(): void
    {
        $this->construct->dataConstruct();
        self::assertNotSame(PHP_SESSION_ACTIVE, session_status());
    }
    public function tearDown(): void
    {
        $connector = new SqlConnector();
        $connector->executeDeleteQuery("DELETE FROM orders;", []);
        $connector->executeDeleteQuery("DELETE FROM user_baskets;", []);
        $connector->executeDeleteQuery("DELETE FROM users;", []);
        $connector->closeConnection();
        parent::tearDown();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}